# Generated by Django 5.0.6 on 2024-05-30 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='type',
        ),
        migrations.AlterModelTable(
            name='code',
            table='project_code',
        ),
        migrations.AlterModelTable(
            name='codetype',
            table='project_code_type',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='project_tag',
        ),
        migrations.AddField(
            model_name='code',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.codetype'),
        ),
    ]
